### ISSUE TITLE
examples中的playerlist.py无法跑通，提示cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by hyf3513OneGO** [MCDReforged/MinecraftDataAPI#2]
环境：
1.16.5原版服
MCDR V1.3
hsjon依赖已经安装

问题情况截图：
![image](https://user-images.githubusercontent.com/67197231/109002202-dbf5c100-76e0-11eb-9760-78f0f353f9f9.png)

**Comment by Fallen-Breath** [comment]
fixed in v1.2.2
