### ISSUE TITLE
在混合验证模式的服务器中获取玩家 UUID

### ISSUE THREAD

**Issue by Nyaacinth** [MCDReforged/MinecraftDataAPI#3]
起因是我目前正在做的一个传送插件计划使用 UUID 辨识不同的玩家，但目标服务器使用了兼容正版登录的自建外置登录服务。这意味着玩家 UUID 生成模式是随机的，不能简单的使用离线或在线模式规则自行生成。于是想到获取世界中的玩家实体 UUID 来保证数据正确。

但当尝试使用 `get_player_info` 获取的时候
`server.get_plugin_instance('minecraft_data_api').get_player_info(player,'UUID')`

出现了以下错误
`[MCDR] [01:09:29] [Thread-1/ERROR]: [Minecraft Data API] Fail to Convert data "Nyaacinth has the following entity data: [I; -1731745998, 114217...": Expecting value: line 1 column 54 (char 53)`

看起来是由于 Minecraft 使用了一种奇特的格式输出信息导致了错误
例：`[I; -1731745998, 1142179115, -1749925876, 1665123830]`

且即使能够获取，这也不是常规的 UUID 格式，仍需要做二次处理，故在此希望能够增加处理实体 UUID 的功能

**Comment by Fallen-Breath** [comment]
服务端版本、类型是？

**Comment by Nyaacinth** [comment]
服务端为 Spigot ，注入 Authlib-injector
版本为 1.16.5 (Spigot-1.16.5-125)

不过在测试 Vanilla 和 Fabric 服务端后大概可以确认各个服务端在实体数据这里有着相同的表现

**Comment by Fallen-Breath** [comment]
已于 v1.3.0 修复，现可正常解析这一类数组
