### ISSUE TITLE
Fail to convert data 若玩家身上的物品nbt帶有AttributeModifier

### ISSUE THREAD

**Issue by B-2U** [MCDReforged/MinecraftDataAPI#4]
[!!hat/ERROR]: [Minecraft Data API] Fail to Convert data "_GieR has the following entity data: [{Slot: 0b, id: "minecraft:...": None

物品nbt:
  `{Slot: 7b, id: "minecraft:oak_button", Count: 1b, tag: {AttributeModifiers: [{AttributeName: "generic.attack_speed", Operation: 0, UUID: [I; -121419, 20178, 232920, -40356], Amount: 4, Name: "generic.attack_speed"}]}}`

已將多種物品(鞋子,胸甲etc) 和 多種attribute(atk.speed, speed, armor...)排列組合 皆會報錯

mc give cmd for debug:
  `/give @p oak_button{AttributeModifiers:[{AttributeName:"generic.attack_speed",Amount:4,Operation:0,UUID:[I;-121419,20178,232920,-40356],Name:"generic.attack_speed"}]} 1`

**Comment by Fallen-Breath** [comment]
出错原因是 `UUID: [I; -121419, 20178, 232920, -40356]` 包含了非标准化的数组格式，同 #1

**Comment by B-2U** [comment]
那請問這應該如何處理才好

**Comment by Fallen-Breath** [comment]
已于 v1.3.0 修复，现可正常解析这一类数组
