### ISSUE TITLE
关于get_player_info()超时跟玩家名前缀的问题（详见issue内容）

### ISSUE THREAD

**Issue by boring-314** [MCDReforged/MinecraftDataAPI#5]
## 问题
使用get_player_info()获取带有名称前缀（原版team前缀功能）的玩家时控制台成功返回mc内`/data`命令的结果但本API仍然提示超时
**已使用针对特定格式玩家名的MCDR服务端处理器**（其实就是[MCDR帮助文档中的示例](https://mcdreforged.readthedocs.io/zh_CN/latest/customize/handler.html#example)，格式也是[prefix]name）**，且除依赖minecraftdataapi的插件以外的插件均能够正常运行**
（这不一定是本API的bug，交issue主要是想求助一下）
## 发现过程
我给服务器制定了称号系统使玩家名拥有了前缀，之后了解了相关信息使用了上面提到的MCDR服务端处理器，本来一切正常，大部分插件、命令比如!!MCDR等都能正常使用，但依赖MinecraftDataAPI的插件却出现了上面说的问题，然后我写了一个测试插件来反复验证问题，最后报错如下：
```
[Server] [20:57:12] [Server thread/INFO]: <[赞助者]boring_314> !!test
[Server] [20:57:12] [Server thread/INFO]: [赞助者]boring_314 has the following entity data: 0
[MCDR] [20:57:17] [test/WARNING]: [Minecraft Data API] Query for player boring_314 at path  playerGameType timeout
```
给客户端的是None
而当我去掉前缀就不会出现问题
```
[Server] [21:43:01] [Server thread/INFO]: <boring_314> !!test
[Server] [21:43:01] [Server thread/INFO]: boring_314 has the following entity data: 0
```
给客户端的就正常了，是0
如何解决它？

测试插件是建立指令!!test，触发后用API的get_player_info(player,'playerGameType')返回玩家的游戏模式然后用server.tell()输出给客户端，全部13行代码在末尾。
系统：Centos 7.3
Python 3.9.5
Java:
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment 21.3 (build 16.0.1+9)
OpenJDK 64-Bit Server VM 21.3 (build 16.0.1+9, mixed mode, sharing)
游戏版本1.17
MinecraftDataAPI版本就是最新的1.3.0
需要其他信息我会再提供

runtest.py:
```
from mcdreforged.plugin.server_interface import ServerInterface
from mcdreforged.api.command import *
from time import sleep
from mcdreforged.api.decorator import new_thread
def on_load(server: ServerInterface, prev):
    api = server.get_plugin_instance('minecraft_data_api')
    @new_thread('test')
    def test(source):
        gtype=api.get_player_info(source.player,'playerGameType')
        server.tell(source.player,gtype)
    server.register_command(
        Literal('!!test').
            runs(test)
    )
```
(其实我之前找过第一个出问题的插件交issue，然后插件作者给我说是MinecraftDataAPI的问题我才来这的)

**Comment by Fallen-Breath** [comment]
https://github.com/MCDReforged/MinecraftDataAPI/blob/db721f11074608a906ae4a65408b1e16821bd8a8/MinecraftDataAPI.py#L71-L72

此处是该 api 匹配服务端回显“xxx has the following entity data: yyy”信息的匹配，仅包含对无前缀玩家名的处理，无法处理带前缀的玩家名

现在暂时没有好的方法可以自适应处理玩家名，不过你可以修改此处代码以让 api 正确地响应你服务器中可能的玩家前缀

**Comment by eagle3236** [comment]
> https://github.com/MCDReforged/MinecraftDataAPI/blob/db721f11074608a906ae4a65408b1e16821bd8a8/MinecraftDataAPI.py#L71-L72
> 
> 此处是该 api 匹配服务端回显“xxx has the following entity data: yyy”信息的匹配，仅包含对无前缀玩家名的处理，无法处理带前缀的玩家名
> 
> 现在暂时没有好的方法可以自适应处理玩家名，不过你可以修改此处代码以让 api 正确地响应你服务器中可能的玩家前缀

既然MCDR可以正确识别带前缀的玩家名，为何不加入 RCON 功能解决这类问题？打开 RCON 功能后数据由 RCON 获取，而不是读服务端输出

**Comment by boring-314** [comment]
经修改API代码，我的问题已成功解决，感谢指导

**Comment by Mooling0602** [comment]
1.5.0版本下我也遇到了这个问题，尝试如截图所示修改正则匹配，但仍然报错
![image](https://github.com/MCDReforged/MinecraftDataAPI/assets/147964268/54c8239c-1284-41e6-a3ee-ae372cd8aae0)
![image](https://github.com/MCDReforged/MinecraftDataAPI/assets/147964268/dd240d17-e795-4f95-8ee8-0c588f14807a)

**Comment by alex3236** [comment]
> 1.5.0版本下我也遇到了这个问题，尝试如截图所示修改正则匹配，但仍然报错

你怎么改的……

**Comment by Mooling0602** [comment]
> > 1.5.0版本下我也遇到了这个问题，尝试如截图所示修改正则匹配，但仍然报错
> 
> 你怎么改的……

__ENTITY_DATE_REGEX = re.compile(r'^#?[a-zA-Z0-9_]{3,16}$ has the following entity data: .*$')

**Comment by Mooling0602** [comment]
> https://github.com/MCDReforged/MinecraftDataAPI/blob/db721f11074608a906ae4a65408b1e16821bd8a8/MinecraftDataAPI.py#L71-L72
> 
> 此处是该 api 匹配服务端回显“xxx has the following entity data: yyy”信息的匹配，仅包含对无前缀玩家名的处理，无法处理带前缀的玩家名
> 
> 现在暂时没有好的方法可以自适应处理玩家名，不过你可以修改此处代码以让 api 正确地响应你服务器中可能的玩家前缀

在1.6.1版本尝试修改代码，发现再次出现无法解析玩家前缀的问题。
在1.5.0尝试修改minecraft_data_api/player_data_getter.py第38行为以下内容，可以正确解析：
```python
        command = 'data get entity "{}"{}'.format(player, path)
``` 
在1.6.1版本，找不到该行内容，后面发现该部分迁移到了minecraft_data_api/config.py，于是将其11至14行修改为以下内容：
```python
class PlayerDataGetterConfig(Serializable):
	data_get_all_command: str = 'data get entity "{player}"'
	data_get_path_command: str = 'data get entity "{player}" {path}'
	data_get_output_regex: re.Pattern = re.compile(r'^(?P<player>^\w+) has the following entity data: .*$')
``` 
发现无法解析。

**Comment by alex3236** [comment]
> ```python
> PlayerDataGetterConfig
> ```

你都发现它在配置里了，那么请修改配置文件而非源码 https://github.com/Fallen-Breath/MinecraftDataAPI?tab=readme-ov-file#configuration

**Comment by Mooling0602** [comment]
> > ```python
> > PlayerDataGetterConfig
> > ```
> 
> 你都发现它在配置里了，那么请修改配置文件而非源码 https://github.com/Fallen-Breath/MinecraftDataAPI?tab=readme-ov-file#configuration

没注意有配置，抱歉）
